### PR TITLE
Adding test of 'time' field for Item 

### PR DESCRIPTION
**Pull request by chaconnewu**
Many posts are deleted, which will cause error access of the 'time' field of an item. Adding testing of 'time' field before accessing.

### CODE REVIEW

**Comment by abrinsmead** [comment]
Good find.  Thanks!

**Comment by abrinsmead** [comment]
I added a CONTRIBUTORS file and pushed the latest version to PyPI.  Thanks again.

**Comment by chaconnewu** [comment]
Thanks a lot :). I really appreciate it.

**Comment by abrinsmead** [comment]
We should update tests.py to test that a deleted Item instance does not raise an exception when Item.time is accessed.  Do you want to do it?

**Comment by chaconnewu** [comment]
Sounds great. Let me handle that and I will send you a pull request then.

On Sun, Nov 2, 2014 at 7:51 PM, Alex Brinsmead notifications@github.com
wrote:

> We should update tests.py to test that a deleted Item instance does not
> raise an exception when Item.time is accessed. Do you want to do it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/abrinsmead/hackernews-python/pull/1#issuecomment-61438202
> .

## 

Wu Yu

**Pull request merged**
